automation:
- alias: Outdoor lights sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: light.hue_ambiance_spot_1
    
- alias: Outdoor lights sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: light.hue_ambiance_spot_1